@startuml

title Usecase EverDance

actor User
actor Epay
actor Fitness_tracker

rectangle Program {
usecase (Авторизувати користувача)
usecase (Підключити фітнес-трекер до застосунку)
usecase (Вибрати тип підписки)
usecase (Оплатити підписку)

(Вибрати тип підписки) .> (Авторизувати користувача) : include
(Оплатити підписку) .> (Вибрати тип підписки) : include
(Підключити фітнес-трекер до застосунку) .> (Авторизувати користувача) : include

Epay -- (Оплатити підписку)
User -- (Авторизувати користувача)
Fitness_tracker -- (Підключити фітнес-трекер до застосунку)

}
@enduml
